[tool]
id = "com.gios.brightrecorderlite"
label = "Recorder Lite"
versionCode = 1
versionName = "0.1.0"
permissions = ["android.permission.RECORD_AUDIO", "android.permission.ACCESS_FINE_LOCATION"]
capabilities = ["detached-audio"]
orientation = "portrait"
# for the LightOS emulator, use the line below and build with -DlightSdk.allowAltServerPackage=true
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"
